// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuITJN2uDo5zUwk2tq51WjTJBecqXp0Iw',
    appId: '1:1010922435983:web:18158b8eef37ed04a147fa',
    messagingSenderId: '1010922435983',
    projectId: 'aquafusion-d0096',
    authDomain: 'aquafusion-d0096.firebaseapp.com',
    storageBucket: 'aquafusion-d0096.appspot.com',
    measurementId: 'G-9MCBVXBT52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW6Vt-6kCCM80yBhO-SjVJCCEqbyU9lhY',
    appId: '1:1010922435983:android:7ffc514a5d5f9d75a147fa',
    messagingSenderId: '1010922435983',
    projectId: 'aquafusion-d0096',
    storageBucket: 'aquafusion-d0096.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASJo8GuPPzkPIkPaLj2iVFw0BkG5tc2f0',
    appId: '1:1010922435983:ios:184055dcef46f960a147fa',
    messagingSenderId: '1010922435983',
    projectId: 'aquafusion-d0096',
    storageBucket: 'aquafusion-d0096.appspot.com',
    iosBundleId: 'com.example.aquafusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASJo8GuPPzkPIkPaLj2iVFw0BkG5tc2f0',
    appId: '1:1010922435983:ios:184055dcef46f960a147fa',
    messagingSenderId: '1010922435983',
    projectId: 'aquafusion-d0096',
    storageBucket: 'aquafusion-d0096.appspot.com',
    iosBundleId: 'com.example.aquafusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuITJN2uDo5zUwk2tq51WjTJBecqXp0Iw',
    appId: '1:1010922435983:web:301ddf7884f9f976a147fa',
    messagingSenderId: '1010922435983',
    projectId: 'aquafusion-d0096',
    authDomain: 'aquafusion-d0096.firebaseapp.com',
    storageBucket: 'aquafusion-d0096.appspot.com',
    measurementId: 'G-HH78G4EGDF',
  );
}
